on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-ui.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Angular
        working-directory: frontend
        run: |
          npm ci
          npm run build -- --configuration production

      - name: Deploy UI
        uses: azure/webapps-deploy@v3
        with:
          app-name: frontend-raraa
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_UI }}
          package: frontend/dist/coo-chat-ui/browser
