name: Deploy .NET API to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - "api-dotnet/**"
      - ".github/workflows/deploy-api-dotnet.yml"
  workflow_dispatch:

jobs:
  build-and-deploy-dotnet-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore api-dotnet/CooChat.Api.csproj

      - name: Build
        run: dotnet build api-dotnet/CooChat.Api.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish api-dotnet/CooChat.Api.csproj --configuration Release --no-build --output ./api-dotnet-publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: backend-netnet
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_API_DOTNET }}
          package: ./api-dotnet-publish
